REATE DATABASE `attachments` DEFAULT CHARACTER SET utf8;
CREATE DATABASE `bloomberg_rss` DEFAULT CHARACTER SET utf8;
CREATE DATABASE `cms_new` DEFAULT CHARACTER SET utf8;
CREATE DATABASE `phpcms` DEFAULT CHARACTER SET utf8;
CREATE DATABASE `shortUrl` DEFAULT CHARACTER SET utf8;
CREATE DATABASE `slate` DEFAULT CHARACTER SET utf8;
CREATE DATABASE `slate_new` DEFAULT CHARACTER SET utf8;
CREATE DATABASE `video` DEFAULT CHARACTER SET utf8;
